{
 "title": "KV",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "response_status", "legendFormat": "{{path}}-{{status}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__range]))"
    }
   ]
  },
  {
   "title": "Total Request ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_total{}", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "99P",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, \n    sum(\n        rate(\n            kv_http_duration_seconds_bucket[5m]\n        )\n    ) by (path, method, le)\n)"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_http_duration_seconds_sum / kv_http_duration_seconds_count",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total DB Keys",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_keys_kv{kv=\"redis\"}",
     "legendFormat": "Total Keys"
    }
   ]
  }
 ]
}