kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.19.1
    extraPortMappings:
      - containerPort: 30100
        hostPort: 30100
      - containerPort: 30101
        hostPort: 30101
      - containerPort: 30102
        hostPort: 30102
  - role: worker
    image: kindest/node:v1.19.1
networking:
  disableDefaultCNI: true # disable kindnet
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet
