dashboardsProvider:
  enabled: enable
  configMapName:
dashboardsConfigMaps:
  - configMapName: mydashboard
    filename: grafana.yaml

## Create datasources from a custom secret
## The secret must contain the files
##
datasources:
  secretName: datasource
